version: '3.8'

# volumes:
#   vol-themes:
#     name: vol-themes
#   vol-plugins:
#     name: vol-plugins
#   vol-uploads:
#     name: vol-uploads

services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "4306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    
  wordpress:
    depends_on:
      - db
    image: wordpress:6
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
    volumes:
      # - ./src/themes:/var/www/html/wp-content/themes:rw
      # - ./src/plugins:/var/www/html/wp-content/plugins:rw
      # - ./src/uploads:/var/www/html/wp-content/uploads:rw
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
